### Classificação de textos para análise de sentimentos

Base de dados 

Instruções:
- O objetivo deste trabalho é criar um modelo binário de aprendizado de máquina para classificação de textos. 
Para isso, será utilizado a base de dados [IMDb](http://ai.stanford.edu/~amaas/data/sentiment/), que consiste de dados textuais de críticas positivas e negativas de filmes
- Uma vez treinado, o modelo deve ter uma função `predict` que recebe uma string como parâmetro e retorna o valor 1 ou 0, aonde 1 significa uma crítica positiva e 0 uma crítica negativa
- O pré-processamento pode ser desenvolvidado conforme desejar (ex.: remoção de stopwords, word embedding, one-hot encoding, char encoding)
- É preferível que seja empregado um modelo de recorrência (ex.: rnn, lstm, gru) para a etapa de classificação
- Documente o código (explique sucintamente o que cada função faz, insira comentários em trechos de código relevantes)
- **Atenção**: Uma vez treinado o modelo final, salve-o no diretório do seu projeto e crie uma célula ao final do notebook contendo uma função de leitura deste arquivo, juntamente com a execução da função `predict`

Sugestões:
- Explorar a base de dados nas células iniciais do notebook para ter um melhor entendimento do problema, distribuição dos dados, etc
- Após desenvolver a estrutura de classificação, é indicado fazer uma busca de hiperparâmetros e comparar os resultados obtidos em diferentes situações

Prazo de entrega:
- 01-08-2021 às 23:59hs GMT-3

Formato preferível de entrega:
- Postar no portal Ava da disciplina o link do projeto no github (ou anexar o projeto diretamente no portal Ava)

luann.porfirio@gmail.com

In [1]:
!pip install torchtext

In [92]:
import nltk
import torch
import numpy as np
import pandas as pd
import torch.nn.functional as F

from nltk.corpus import stopwords
from torchtext import datasets
from torch import nn
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Dataset, DataLoader, random_split
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.callbacks import ModelCheckpoint   # save model

In [3]:
train_iter, test_iter = datasets.IMDB()

In [4]:
dataset_imdb = list(train_iter + test_iter)

In [5]:
df_imdb_raw = pd.DataFrame(data=dataset_imdb, columns=['sentiment', 'review'])

In [6]:
df_imdb_raw.shape

(50000, 2)

In [7]:
df_imdb_raw.head()

sentiment                                             review
0       neg  I rented I AM CURIOUS-YELLOW from my video sto...
1       neg  "I Am Curious: Yellow" is a risible and preten...
2       neg  If only to avoid making this type of film in t...
3       neg  This film was probably inspired by Godard's Ma...
4       neg  Oh, brother...after hearing about this ridicul...

In [8]:
df_imdb_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  50000 non-null  object
 1   review     50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB


In [9]:
df_imdb_raw.describe()

sentiment                                             review
count      50000                                              50000
unique         2                                              49582
top          neg  Loved today's show!!! It was a variety and not...
freq       25000                                                  5

In [10]:
df_imdb_raw.nunique()

sentiment        2
review       49582
dtype: int64

In [11]:
df_imdb_raw.head()

sentiment                                             review
0       neg  I rented I AM CURIOUS-YELLOW from my video sto...
1       neg  "I Am Curious: Yellow" is a risible and preten...
2       neg  If only to avoid making this type of film in t...
3       neg  This film was probably inspired by Godard's Ma...
4       neg  Oh, brother...after hearing about this ridicul...

In [12]:
df_imdb_raw.tail()

sentiment                                             review
49995       pos  Just got around to seeing Monster Man yesterda...
49996       pos  I got this as part of a competition prize. I w...
49997       pos  I got Monster Man in a box set of three films ...
49998       pos  Five minutes in, i started to feel how naff th...
49999       pos  I caught this movie on the Sci-Fi channel rece...

In [13]:
df_imdb_raw[df_imdb_raw.duplicated()]

sentiment                                             review
168         neg  I am not so much like Love Sick as I image. Fi...
664         neg  Holy freaking God all-freaking-mighty. This mo...
701         neg  The story and the show were good, but it was r...
3070        neg  I watched this movie when Joe Bob Briggs hoste...
3591        neg  I like Chris Rock, but I feel he is wasted in ...
...         ...                                                ...
49911       pos  I watched Pola X because Scott Walker composed...
49912       pos  Leos Carax has made 3 great movies: Boys Meet ...
49913       pos  Leos Carax is brilliant and is one of the best...
49914       pos  I've tried to reconcile why so many bad review...
49962       pos  I have seen most of the Tarzan episodes. Certa...

[418 rows x 2 columns]

Necessário remover stopwords, caracteres que não são alfabeto e transformar para lowercase.

Há também casos duplicados.

Pré processamento

In [14]:
df_cleaned = df_imdb_raw.drop_duplicates()

In [15]:
df_cleaned.describe()

sentiment                                             review
count      49582                                              49582
unique         2                                              49582
top          pos  1981's Just Before Dawn is one of the best tal...
freq       24884                                                  1

In [16]:
nltk.download('stopwords')
english_stops = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [19]:
df_cleaned['review'] = df_cleaned['review'].replace({'<.*?>': ''}, regex = True)
df_cleaned['review'] = df_cleaned['review'].replace({'[^A-Za-z]': ' '}, regex = True)
df_cleaned['review'] = df_cleaned['review'].apply(lambda review: [w for w in review.split() if w not in english_stops])
df_cleaned['review'] = df_cleaned['review'].apply(lambda review: [w.lower() for w in review])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [20]:
df_cleaned['sentiment'] = df_cleaned['sentiment'].replace('neg', 0)
df_cleaned['sentiment'] = df_cleaned['sentiment'].replace('pos', 1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [29]:
df_cleaned.head()

sentiment                                             review
0          0  [i, rented, i, am, curious, yellow, video, sto...
1          0  [i, am, curious, yellow, risible, pretentious,...
2          0  [if, avoid, making, type, film, future, this, ...
3          0  [this, film, probably, inspired, godard, mascu...
4          0  [oh, brother, hearing, ridiculous, film, umpte...

In [30]:
df_cleaned.tail()

sentiment                                             review
49995          1  [just, got, around, seeing, monster, man, yest...
49996          1  [i, got, part, competition, prize, i, watched,...
49997          1  [i, got, monster, man, box, set, three, films,...
49998          1  [five, minutes, started, feel, naff, looking, ...
49999          1  [i, caught, movie, sci, fi, channel, recently,...

In [31]:
all_text = [item for sublist in [w for w in df_cleaned['review']] for item in sublist]

In [32]:
len(all_text)

6436912

In [33]:
chars = tuple(set(all_text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

encoded = np.array([char2int[ch] for ch in all_text])

In [82]:
X = df_cleaned.drop('sentiment', axis=1)

In [83]:
le = LabelEncoder()
y = le.fit_transform(df_cleaned['sentiment'].values)

In [84]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [86]:
x_train = x_train['review']

In [87]:
# ENCODE REVIEW
token = Tokenizer(lower=False)    # no need lower, because already lowered the data in load_data()
token.fit_on_texts(x_train)
x_train = token.texts_to_sequences(x_train)
x_test = token.texts_to_sequences(x_test)

In [88]:
def get_max_length():
    review_length = []
    for review in x_train:
        review_length.append(len(review))

    return int(np.ceil(np.mean(review_length)))

In [89]:
max_length = get_max_length()

x_train = pad_sequences(x_train, maxlen=max_length, padding='post', truncating='post')
x_test = pad_sequences(x_test, maxlen=max_length, padding='post', truncating='post')

total_words = len(token.word_index) + 1   # add 1 because of 0 padding

print('Encoded X Train\n', x_train, '\n')
print('Encoded X Test\n', x_test, '\n')
print('Maximum review length: ', max_length)

Encoded X Train
 [[    1    13   422 ...     0     0     0]
 [    7     9    65 ...     0     0     0]
 [    8     4   143 ...     0     0     0]
 ...
 [    1   162     4 ...     0     0     0]
 [  144 13555   154 ...     0     0     0]
 [    2 11824   183 ...     0     0     0]] 

Encoded X Test
 [[614   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0]] 

Maximum review length:  130


In [100]:
def one_hot_encode(arr, n_labels):
    
    # Inicializa array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Preenche com valor 1
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Reshape
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [101]:
def get_batches(arr, batch_size, seq_length):
    
    batch_size_total = batch_size * seq_length
    n_batches = len(arr)//batch_size_total
    
    arr = arr[:n_batches * batch_size_total]
    arr = arr.reshape((batch_size, -1))
    
    for n in range(0, arr.shape[1], seq_length):
        x = arr[:, n:n+seq_length]
        y = np.zeros_like(x)
        try:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, n+seq_length]
        except IndexError:
            y[:, :-1], y[:, -1] = x[:, 1:], arr[:, 0]
        yield x, y

Define a arquitetura

In [24]:
nltk.download('stopwords')
english_stops = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [34]:
class ImdbDataset(Dataset):
    """Imdb Dataset."""

    def __init__(self, df_raw):
      df_cleaned = df_raw

      df_cleaned['review'] = df_cleaned['review'].replace({'<.*?>': ''}, regex = True)
      df_cleaned['review'] = df_cleaned['review'].replace({'[^A-Za-z]': ' '}, regex = True)
      df_cleaned['review'] = df_cleaned['review'].apply(lambda review: [w for w in review if w not in english_stops])
      df_cleaned['review'] = df_cleaned['review'].apply(lambda review: [w.lower() for w in review])

      #df_cleaned['review_chars'] = df_cleaned['review'].apply(lambda x: tuple(set(x)))
      #df_cleaned['review_int2char'] = df_cleaned['review_chars'].apply(lambda x: dict(enumerate(x)))
      #df_cleaned['review_char2int'] = df_cleaned['review_int2char'].apply(lambda x: {ch: ii for ii, ch in x.items()})
      #df_cleaned['review_encoded'] = df_cleaned['review'].apply(self.encode_review)

      self.all_text = [item for sublist in [w for w in df_cleaned['review']] for item in sublist]
      self.chars = tuple(set(self.all_text))
      self.int2char = dict(enumerate(self.chars))
      self.char2int = {ch: ii for ii, ch in self.int2char.items()}

      self.encoded = np.array([self.char2int[ch] for ch in self.all_text])

      self.imdb_frame = df_cleaned

      # Save target and predictors
      self.X = self.imdb_frame.drop('sentiment', axis=1)

      le = LabelEncoder()
      self.y = le.fit_transform(self.imdb_frame['sentiment'].values)

    def __len__(self):
      return len(self.imdb_frame)

    def __getitem__(self, idx):
      if torch.is_tensor(idx):
          idx = idx.tolist()

      features = self.X.iloc[idx].values
      print(features)
      target = self.y[idx].astype(str).astype(int)
      print(target)

      sample = [features, target]

      return sample

    def encode_review(self, x: str):
      chars = tuple(set(x))
      int2char = dict(enumerate(chars))
      char2int = {ch: ii for ii, ch in int2char.items()}
      return np.array([char2int[ch] for ch in x])

In [35]:
imdb_dataset = ImdbDataset(df_imdb_raw)

In [36]:
# Split into training and test
train_size = int(0.7 * len(imdb_dataset))
test_size = len(imdb_dataset) - train_size
trainset, testset = random_split(imdb_dataset, [train_size, test_size])

In [37]:
# Dataloaders
train_dataloader = DataLoader(trainset, batch_size=200, shuffle=True)
test_dataloader = DataLoader(testset, batch_size=200, shuffle=False)

In [90]:
class ImdbLSTM(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        #definir lstm input_size, hidden_size, num_layers
        self.lstm = nn.LSTM(len(self.chars), n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
        
        #definir dropout
        self.dropout = nn.Dropout(drop_prob)
        
        #definir camada fc num_hidden input_size
        self.fc = nn.Linear(n_hidden, len(self.chars))
      
    
    def forward(self, x, hidden):
                
        r_output, hidden = self.lstm(x, hidden)
        
        out = self.dropout(r_output)
        out = out.contiguous().view(-1, self.n_hidden)
        out = self.fc(out)
        
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        # Gera tensores de tamanho n_layers x betch_size x n_hidden
        weight = next(self.parameters()).data
        hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        
        return hidden

In [93]:
checkpoint = ModelCheckpoint(
    'models/LSTM.h5',
    monitor='accuracy',
    save_best_only=True,
    verbose=1
)

In [97]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    #dados de treino/validacao
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encoding
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            # Cria variáveis para hidden state 
            h = tuple([each.data for each in h])

            net.zero_grad()
            
            # saida do modelo
            output, h = net(inputs, h)
            
            loss = criterion(output, targets.view(batch_size*seq_length).long())
            loss.backward()
            
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            if counter % print_every == 0:
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.view(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() 
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

Treinamento

In [98]:
n_hidden=256
n_layers=2

net = ImdbLSTM(chars, n_hidden, n_layers)
print(net)

ImdbLSTM(
  (lstm): LSTM(101397, 256, num_layers=2, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=256, out_features=101397, bias=True)
)


In [ ]:
batch_size = 128
seq_length = 100
n_epochs = 110

train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)